[tasks.watch]
run_task = [
    { name = ["clippy", "test"]}
]
watch = true

[task.clippy]
command = "cargo"
args = ["clippy"]

[task.test]
command = "cargo"
args = ["test"]

// cargo make watch でwatchタスクを実行できる